# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c66194248b9f3890e9f6892f2802fcfae108b305148930e415168eb09bd4777b28a3b1d20f365e25337f0ebab8d40473b0b0b2b950f3a644e145614456d4b3

test:
  secret_key_base: c660403d573ac4cd6ab226577c45a7643161b887df5429fef2e91b1131abbf658f6a0b715a5ac9607a2319498a328678283e4a319fad3ecb4620598504c4c60f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
